### ISSUE TITLE
Private function and doc

### ISSUE THREAD

**Issue by apoyet** [sterbini/cl2pd#1]
First try here, I hope it can be a good way to work. 

You defined two function cals2pd, one "private" one not. I do see a problem with the documentation. Indeed, a user shall use the "public" function. If this user wants to see the code, he will just see that this function is calling another "private" one. Couldn't it be confusing? Why do you really want to have a private version of the function?

**Comment by sterbini** [comment]
Hi,
thank you for your comment.
cals2pd calls several times  _cals2pd. In fact, _cals2pd has not the ''splitting" feature.
In order to properly maintain/debug/improve the code, I build complex functions starting from easier (providing less features) ones.
Do we agree? If not fork your proposal. LEt 
Cheers,
G.

**Comment by sterbini** [comment]
Hi,
I changed the name of the private function to reduce the confusion (_cals2pd became _noSplitcals2pd).
Thanks again for sharing your idea.
Cheers,
G.
